// Transcripción del catálogo de WhatsApp de Xiliana Boutique, 2 de octubre de 2026.
// Los precios y tallas pueden cambiar; la boutique confirma disponibilidad.
export const products = [
  { id: 1, name: 'Vestido de largo gala nude con aplicaciones', category: 'Gala', price: 649, note: 'Prenda importada' },
  { id: 2, name: 'Vestido largo de gala de lentejuelas rojo brillantes', category: 'Gala', price: 649, note: 'Talla XL indicada en WhatsApp', imageNote: 'La foto visible en WhatsApp muestra un vestido oscuro multicolor; confirma el modelo con la boutique.' },
  { id: 3, name: 'Vestido sirena largo color rojo con Bruselas', category: 'Gala', price: 449, note: 'Prenda importada, según el catálogo.' },
  { id: 4, name: 'Vestido romano largo floreado', category: 'Largos', price: 439 },
  { id: 5, name: 'Vestido largo fucsia', category: 'Largos', price: 389 },
  { id: 6, name: 'Vestido largo amarillo con lazo', category: 'Largos', price: 449, note: 'Strapless de gasa con lazo en la cintura, según el catálogo.' },
  { id: 7, name: 'Vestido corto azul', category: 'Cortos con brillo', price: 329 },
  { id: 8, name: 'Vestido corto verde', category: 'Cortos con brillo', price: 114.50, originalPrice: 229, note: 'Tallas S y M indicadas en WhatsApp.' },
  { id: 9, name: 'Vestido corto de lentejuelas verde', category: 'Cortos con brillo', price: 369 },
  { id: 10, name: 'Vestido corto azul con estampado floral', category: 'Cortos', price: 68.70, originalPrice: 229, note: 'Mangas y silueta ajustada, según el catálogo.' },
  { id: 11, name: 'Vestido corto satín estampado', category: 'Cortos', price: 86.70, originalPrice: 289 },
  { id: 12, name: 'Vestido corto con volantes de cuello redondo', category: 'Cortos', price: 115.60, originalPrice: 289 },
  { id: 13, name: 'Vestido bandage blanco y negro', category: 'Bandage', price: 144.50, originalPrice: 289 },
  { id: 14, name: 'Vestido bandage verde con rayas', category: 'Bandage', price: 379 },
  { id: 15, name: 'Vestido bandage rojo corto con pedrería plateada', category: 'Bandage', price: 379 },
  { id: 16, name: 'Vestido transparente con diamantes de imitación', category: 'Liquidación', price: 164.50, originalPrice: 329, note: 'Talla L indicada en WhatsApp.' },
  { id: 17, name: 'Vestido corto dorado de una manga', category: 'Liquidación', price: 194.50, originalPrice: 389 },
  { id: 18, name: 'Vestido estampado floreado', category: 'Largos', price: 629 },
  { id: 19, name: 'Vestido largo floreado de tirantes', category: 'Largos', price: 499 },
  { id: 20, name: 'Vestido rojo largo de manga abanicada', category: 'Largos', price: 289 },
  { id: 21, name: 'Vestido largo anaranjado de mangas largas de rosas', category: 'Largos', price: 369 },
  { id: 22, name: 'Vestido blanco de corte sirena de manga larga de rosas', category: 'Largos', price: 349 },
  { id: 23, name: 'Vestido largo crema de mangas', category: 'Largos', price: 319 },
  { id: 24, name: 'Vestido largo amarillo corte romano', category: 'Largos', price: 449 },
  { id: 25, name: 'Vestido largo verde limón', category: 'Largos', price: 599 },
  { id: 26, name: 'Vestido largo animal print', category: 'Largos', price: 599 },
  { id: 27, name: 'Vestido largo bandage rojo', category: 'Bandage', price: 549 },
  { id: 28, name: 'Vestido largo floreado', category: 'Largos', price: 449 },
  { id: 29, name: 'Vestido estampado multicolor', category: 'Largos', price: 289 },
  { id: 30, name: 'Vestido animal print multicolor', category: 'Largos', price: 329 },
  { id: 31, name: 'Vestido floreado multicolor', category: 'Largos', price: 349 },
  { id: 32, name: 'Vestido largo blanco con estampado de flores', category: 'Largos', price: 269 },
  { id: 33, name: 'Vestido corte A animal print', category: 'Largos', price: 349 },
  { id: 34, name: 'Vestido de lentejuelas corto rojo', category: 'Cortos con brillo', price: 289 },
  { id: 35, name: 'Vestido corto de una manga color marrón', category: 'Cortos con brillo', price: 389 },
  { id: 36, name: 'Vestido corto negro con plateado', category: 'Cortos con brillo', price: 75.60, originalPrice: 189 },
  { id: 37, name: 'Vestido corto negro con mangas plateadas', category: 'Cortos con brillo', price: 119.50, originalPrice: 239 },
  { id: 38, name: 'Vestido corto de lentejuelas rosado de una manga', category: 'Cortos con brillo', price: 389 },
  { id: 39, name: 'Vestido verde de lentejuelas y mostacillas', category: 'Cortos con brillo', price: 329 },
  { id: 40, name: 'Vestido corto 3/4 de lentejuelas con terciopelo en el busto', category: 'Cortos con brillo', price: 399 },
  { id: 41, name: 'Vestido de lentejuelas palo rosa de transparencias', category: 'Cortos con brillo', price: 389 },
  { id: 42, name: 'Vestido corto negro con tirantes y pedrería', category: 'Cortos con brillo', price: 399 },
  { id: 43, name: 'Vestido corto champagne de lentejuelas con cuello alto', category: 'Cortos con brillo', price: 389 },
  { id: 44, name: 'Vestido corto blanco de lentejuelas tornasoladas', category: 'Cortos con brillo', price: 349 },
  { id: 45, name: 'Vestido corto de tirantes con pedrería', category: 'Cortos con brillo', price: 369 },
  { id: 46, name: 'Vestido corto rojo de pedrería', category: 'Cortos con brillo', price: 329 },
  { id: 47, name: 'Vestido corto verde de pedrería plateada y perlas', category: 'Cortos con brillo', price: 399 },
  { id: 48, name: 'Vestido largo de lentejuelas con diamantes', category: 'Largos', price: 349 },
  { id: 49, name: 'Vestido corto rojo de lentejuelas', category: 'Cortos con brillo', price: 298 },
  { id: 50, name: 'Vestido corto blanco con dorado de lentejuelas', category: 'Cortos con brillo', price: 369 },
  { id: 51, name: 'Vestido corto de lentejuelas celeste y azul', category: 'Cortos con brillo', price: 449 },
  { id: 52, name: 'Vestido corto asimétrico de lentejuelas azul', category: 'Cortos con brillo', price: 389 },
  { id: 53, name: 'Vestido corto azul de lentejuelas y flecos', category: 'Cortos con brillo', price: 389 },
  { id: 54, name: 'Vestido corto de diamantes de imitación plateadas', category: 'Cortos con brillo', price: 349 },
  { id: 55, name: 'Vestido de pedrería negro con plumas', category: 'Cortos con brillo', price: 469 },
  { id: 56, name: 'Vestido corto azul de pedrería y strass', category: 'Cortos con brillo', price: 389 },
  { id: 57, name: 'Vestido corto blanco de lentejuelas', category: 'Cortos con brillo', price: 349 },
  { id: 58, name: 'Vestido dorado corto asimétrico de flecos', category: 'Cortos con brillo', price: 389 },
].map(product => ({ ...product, image: `./images/${product.id <= 17 ? 'dress' : 'catalog'}-${String(product.id).padStart(2, '0')}.jpg` }));

export const categories = ['Todos', 'Gala', 'Largos', 'Cortos con brillo', 'Cortos', 'Bandage', 'Liquidación'];
