from pathlib import Path
import re,json
root=Path(__file__).resolve().parents[1]
f=root/'products.js';s=f.read_text(encoding='utf-8')
s=re.sub(r"  const originalImage = .*?;\n",'',s)
s=s.replace('return { ...product, originalImage, photos, image: photos[0]?.src || originalImage };',"return { ...product, photos, image: photos[0]?.src || './images/foto-pendiente.svg', photoPending: !photos.length };")
f.write_text(s,encoding='utf-8')
f=root/'main.js';s=f.read_text(encoding='utf-8').replace("image: './images/dress-01.jpg'","image: './images/xiliana-logo-gold-black.png'")
s=s.replace('.filter(product => (activeCategory', '.filter(product => !product.photoPending && (activeCategory')
s=s.replace('Captura original del catálogo. Consulta más fotos con la boutique.','Foto real pendiente. Consulta el modelo con la boutique.')
f.write_text(s,encoding='utf-8')
f=root/'index.html';s=f.read_text(encoding='utf-8').replace('poster="./images/dress-01.jpg"','poster="./images/xiliana-logo-gold-black.png"').replace('id="product-count">58','id="product-count">20').replace('real-photos-1','real-photos-2');f.write_text(s,encoding='utf-8')
f=root/'seo-build.cjs';s=f.read_text(encoding='utf-8')
s=re.sub(r'  const dimensions = p => .*?;\n', '  const dimensions = p => p.photos.length ? `width="${p.photos[0].width}" height="${p.photos[0].height}"` : \'width="900" height="1200"\';\n',s,count=1)
s=s.replace("'./images/dress-01.jpg'","'./images/xiliana-logo-gold-black.png'")
s=s.replace('const ordered = [...products].sort','const ordered = products.filter(p => !p.photoPending).sort')
s=s.replace('displayImage(items[0])', "items.length ? displayImage(items[0]) : './images/xiliana-logo-gold-black.png'")
s=s.replace('Captura original del catálogo. Consulta más fotos con la boutique.','Foto real pendiente. Consulta el modelo con la boutique.')
s=s.replace('image: (p.photos.length ? p.photos.map(photo => absolute(photo.src)) : [absolute(displayImage(p))]),', '...(p.photos.length ? {image:p.photos.map(photo => absolute(photo.src))} : {}),')
s=s.replace('images: p.photos.length ? p.photos.map(photo => photo.src) : [displayImage(p)]','images: p.photos.map(photo => photo.src)')
s=s.replace('real-photos-1','real-photos-2')
f.write_text(s,encoding='utf-8')
f=root/'validate-seo.cjs';s=f.read_text(encoding='utf-8')
s=s.replace("      assert(Array.isArray(product.image) && product.image.length > 0);", "      if (!product.image) continue;\n      assert(Array.isArray(product.image) && product.image.length > 0);")
s=s.replace("assert(fs.readFileSync(path.join(output, 'index.html'), 'utf8').includes('data-id=\"58\"'));", "assert(fs.readFileSync(path.join(output, 'index.html'), 'utf8').includes('data-id=\"57\"'));\nassert(!fs.readFileSync(path.join(output, 'index.html'), 'utf8').includes('data-id=\"58\"'));")
f.write_text(s,encoding='utf-8')
manifest=json.loads((root/'review/real-classification.json').read_text(encoding='utf-8'))
for p in manifest['withoutNewPhotos']:p['reason']='Captura recortada eliminada a petición del dueño de la web; pendiente de foto real'
(root/'review/real-classification.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
(root/'pendientes-dueno/PRODUCTOS-SIN-FOTO-REAL.json').write_text(json.dumps(manifest['withoutNewPhotos'],ensure_ascii=False,indent=2),encoding='utf-8')
f=root/'README.md';s=f.read_text(encoding='utf-8');s+='\n## Retirada de capturas recortadas\n\nSe eliminaron las 58 capturas dress-XX.jpg y catalog-XX.jpg por solicitud del usuario. Se muestran 20 productos con fotos reales en el catálogo. Las 38 fichas restantes conservan sus datos y URL con aviso de foto pendiente, sin capturas ni imágenes de IA. Sus datos están en pendientes-dueno/PRODUCTOS-SIN-FOTO-REAL.json. Los originales nuevos y el logo se conservan.\n';f.write_text(s,encoding='utf-8')
print('Referencias actualizadas; 38 productos pendientes registrados para el dueño.')
