(() => {
 const data=JSON.parse(document.getElementById('selection-data').textContent);
 const key='xiliana-asignaciones-v1';let answers={};
 try{answers=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
 const box=document.createElement('section');box.id='asignar';
 box.innerHTML=`<h2>Encuentra el vestido</h2><p>Elige un producto y toca todas sus fotos, incluida la espalda. Usa «Ver grande» para comprobar los detalles. Tus selecciones se guardan en este navegador; descarga el archivo al terminar y pásamelo.</p><label>Producto del catálogo <select id="product-choice"></select></label><p id="choice-info"></p><div class="actions"><button id="none">Ninguna coincide</button><button id="clear-choice">Quitar selección de este vestido</button><button id="download">Descargar mis asignaciones</button></div><p id="selection-status" role="status" aria-live="polite"></p><label>Mostrar <select id="photo-filter"><option value="suggested">Parecidos sugeridos</option><option value="all">Todas las fotos pendientes</option><option value="selected">Mis fotos seleccionadas</option></select></label><div id="photo-game"></div><h3>Mis asignaciones</h3><div id="my-answers"></div>`;
 document.querySelector('h1').after(box);
 const style=document.createElement('style');style.textContent=`#asignar{border:2px solid #92702c;margin-top:24px}select,button{font:inherit;padding:12px;border:1px solid #888;border-radius:5px;background:white;color:#222}select{max-width:100%;display:block;margin:8px 0}button{cursor:pointer}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid #175faa;outline-offset:3px}.actions{display:flex;gap:8px;flex-wrap:wrap}#download{background:#222;color:white}#photo-game{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:16px;margin-top:20px}.pick{border:2px solid #ccc;padding:8px}.pick.chosen{border-color:#176142;background:#eaf7ef}.pick button{width:100%;border:0;padding:0;background:transparent}.pick img{width:100%;height:245px;object-fit:contain}.pick a{display:block;padding:8px;color:#194c78}.pick span{display:block;padding:8px;font-weight:600}#my-answers p{border-bottom:1px solid #ddd;padding-bottom:12px}`;document.head.append(style);
 const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 data.products.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.nombre+' · '+(p.precio==null?'Precio pendiente':'S/ '+p.precio.toFixed(2));$('product-choice').append(o)});
 const current=()=>data.products[+$('product-choice').value];
 function save(){try{localStorage.setItem(key,JSON.stringify(answers))}catch{$('selection-status').textContent='Descarga tus respuestas para conservarlas.'}}
 function render(){const p=current(),a=answers[p.id]||{indices:[]};
 $('choice-info').textContent=p.suggested.length?'Hay fotos parecidas sugeridas. Puedes elegir también entre todas las pendientes.':'No hay un parecido sugerido. Revisa todas las fotos pendientes.';
 let mode=$('photo-filter').value;if(mode==='suggested'&&!p.suggested.length){mode='all';$('photo-filter').value='all'}
 const photos=data.photos.filter(x=>mode==='all'||(mode==='selected'?a.indices.includes(x.index):p.suggested.includes(x.index)));
 $('photo-game').innerHTML='';photos.forEach(x=>{const owner=Object.entries(answers).find(([id,v])=>id!==p.id&&v.indices.includes(x.index));const chosen=a.indices.includes(x.index);const tile=document.createElement('div');tile.className='pick'+(chosen?' chosen':'');tile.innerHTML=`<button type="button" aria-pressed="${chosen}" aria-label="${chosen?'Quitar':'Seleccionar'} foto R${String(x.index).padStart(3,'0')}"><img loading="lazy" src="${esc(x.src)}" alt="Foto original R${x.index}"><span>${chosen?'✓ Seleccionada':'Seleccionar'} · R${String(x.index).padStart(3,'0')}</span></button><a href="${esc(x.src)}" target="_blank" rel="noopener">Ver grande ↗</a>${owner?'<small>Asignada a otro vestido</small>':''}`;
 tile.querySelector('button').onclick=()=>{if(owner){$('selection-status').textContent='Esta foto ya está asignada a otro vestido. Quita primero esa asignación.';return}const next=answers[p.id]||{indices:[]};next.ninguna=false;next.indices=chosen?next.indices.filter(i=>i!==x.index):[...next.indices,x.index];answers[p.id]=next;save();render()};$('photo-game').append(tile)});
 $('selection-status').textContent=a.ninguna?'Marcaste que ninguna foto coincide.':a.indices.length+' fotos seleccionadas para este vestido.';
 $('my-answers').innerHTML=Object.entries(answers).filter(([,a])=>a.indices.length||a.ninguna).map(([id,a])=>{const p=data.products.find(p=>p.id===id);return p?`<p><strong>${esc(p.nombre)}</strong><br>${a.ninguna?'Ninguna coincide':a.indices.map(i=>'R'+String(i).padStart(3,'0')).join(', ')}</p>`:''}).join('')||'<p>Aún no has asignado fotos.</p>';
 }
 $('product-choice').onchange=()=>{$('photo-filter').value='suggested';render()};$('photo-filter').onchange=render;
 $('none').onclick=()=>{answers[current().id]={indices:[],ninguna:true};save();render()};$('clear-choice').onclick=()=>{delete answers[current().id];save();render()};
 $('download').onclick=()=>{const rows=Object.entries(answers).map(([id,a])=>({producto:data.products.find(p=>p.id===id),...a}));const blob=new Blob([JSON.stringify({fecha:new Date().toISOString(),asignaciones:rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='XILIANA-mis-asignaciones.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 render();
})();
